# golang test for this repo
name: golang test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: golang test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      # install go dependencies
      - name: Install dependencies
        run: go mod download
      - name: Go Get
        run: go get github.com/dli-invest/sec-parser-go
      - name: Run tests
        run: go test ./... -v -covermode=count